### ISSUE TITLE
用QUALITIS-AUTH连接Linkis之后，数据源如何配置查询不到

### ISSUE THREAD

**Issue by htcud** [WeBankFinTech/Qualitis#105]
用QUALITIS-AUTH登陆之后，Linkis数据源如何配置查询不到。如何给QUALITIS-AUTH认证方式的用户添加数据源

**Comment by htcud** [comment]
自己的问题，linkis没配置好

**Comment by super3one** [comment]
> 自己的问题，linkis没配置好

我也出现了这个问题，请问最后你是怎么解决的呢

**Comment by figodeng** [comment]
> > 自己的问题，linkis没配置好
> 
> 我也出现了这个问题，请问最后你是怎么解决的呢

求具体原因和解决方案
