### ISSUE TITLE
多指标校验具体使用中出现问题

### ISSUE THREAD

**Issue by xiaohunlt** [WeBankFinTech/Qualitis#107]
**Describe the bug**
没有多指标校验的具体用户手册，所以仿照单指标校验的语句进行规则建立。执行失败，日志如下。
![image](https://user-images.githubusercontent.com/13626310/167113145-840f34d4-3c0a-4eb8-b66b-e089d6f0f0a9.png)

**To Reproduce**
1. 设置指标

![C4A94C94-D79F-463b-8B2C-2B840BFA3306](https://user-images.githubusercontent.com/13626310/167113370-ae726ae3-9f60-4cf5-b3dd-06f30c6d5b71.png)

2.配置多指标规则
![image](https://user-images.githubusercontent.com/13626310/167113509-76c02854-cf70-4753-9bb8-943981ae1dc1.png)

3.选择指标

![image](https://user-images.githubusercontent.com/13626310/167113610-e657cd10-c93e-45ac-a4e4-2d7a16bea463.png)

4.运行该规则

**Expected behavior**
失败
![image](https://user-images.githubusercontent.com/13626310/167113982-966cbd04-8c29-444f-936d-a32d14c23d8b.png)

**Desktop (please complete the following information):**
 - OS: [win10]
 - Browser [chrome]
 - Version [100.0.4896.127]

**Additional context**
引擎失败日志如下
2022-05-06 15:56:06.060 ERROR [Linkis-Default-Scheduler-Thread-14] com.webank.wedatasphere.linkis.engineplugin.spark.executor.SparkScalaExecutor 61 error - Execute code error for org.apache.spark.sql.AnalysisException: cannot resolve '`ehr_2_level_metric_ehrbasic_Daily`' given input columns: [maxnl]; line 1 pos 4;
'Project ['max('ehr_2_level_metric_ehrbasic_Daily) AS value#357, QUALITIS20220506155554621_151143 AS application_id#358, Long AS result_type#359, 15 AS rule_id#360, 1 AS rule_metric_id#361, -1 AS run_date#362, 2022-05-06 15:55:54 AS create_time#363]
+- Project [max(nl)#340 AS maxnl#342]
   +- Aggregate [max(nl#296) AS max(nl)#340]
      +- SubqueryAlias `ods`.`ehr_view_api_report_employee`
         +- HiveTableRelation `ods`.`ehr_view_api_report_employee`, org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe, [gh#292, xm#293, sybz#294, xb#295, nl#296, jg#297, zzmm#298, zjh#299, bm#300, yglx#301, ygzt#302, rzsj#303, lzrq#304, zyjsdj#305, zgxl#306, xygs#307, xylx#308, ssgjdq#309, ywhwqxgzjl#310, ngw#311, zpid#312, agw#313, agw1#314, zjdl#315, ... 23 more fields]

对比单指标检验成功时的日志为
![lQLPDhtl9Vr7dJLNAYXNB2GwcaioXb5jGqsCd7jLvMA8AA_1889_389](https://user-images.githubusercontent.com/13626310/167115245-9328ae4b-bb09-410c-adca-41d7f7e89d72.png)

**Comment by Tangjiafeng** [comment]
Try this:
select max(nl) as <your_metric_name_below> from xxxx
