### ISSUE TITLE
Qualitis starts successfully but the main page cannot be accessed.

### ISSUE THREAD

**Issue by looperEit** [WeBankFinTech/Qualitis#109]
Qualitis starts successfully but the main page cannot be accessed.
![image](https://user-images.githubusercontent.com/46367388/168429146-f0d1095f-ff52-4610-90c8-97126407a6ea.png)
![image](https://user-images.githubusercontent.com/46367388/168429155-ae678b95-09c0-450e-9f53-7b3483383134.png)

firewall message
![image](https://user-images.githubusercontent.com/46367388/168429199-580ade90-6eb9-4d00-969d-aac85451d5b7.png)

**Comment by Tangjiafeng** [comment]
show some backend log please.
