### ISSUE TITLE
Qualitis 0.9.0前端页面不渲染接收到的数据源信息？

### ISSUE THREAD

**Issue by weidong5** [WeBankFinTech/Qualitis#110]
![image](https://user-images.githubusercontent.com/87799321/168477381-9dec65ef-51c0-41d2-93e6-b61c4f9ec6d2.png)
是bug还是我哪里配置问题？

**Comment by lifei1234** [comment]
同问，我的是0.9.1

**Comment by lifei1234** [comment]
@weidong5 你解决了吗

**Comment by weidong5** [comment]
> 

说是这部分还没开源，前端代码不完整

**Comment by Tangjiafeng** [comment]
Version will be planned early next month.

**Comment by jiaojinnaozhixiangmingzi** [comment]
> Version will be planned early next month.

Qualitis 0.9.2前端也是这个情况，是还没有发布到这个版本吗？
