### ISSUE TITLE
Qualitis前端页面无法登陆，报错Can not get username from sso

### ISSUE THREAD

**Issue by xyh15864643181** [WeBankFinTech/Qualitis#124]
![image](https://user-images.githubusercontent.com/62532042/178666451-e5e99158-ffb8-4042-aed4-e2225a896028.png)
如上图所示，在输入账号密码后，点击登录无任何反映
![image](https://user-images.githubusercontent.com/62532042/178666569-31569ef5-a177-4934-96b5-9ad71275d44c.png)
查看logs下的日志，报错如上图所示，应该如何解决？

**Comment by Tangjiafeng** [comment]
请使用最新的 release 安装测试。
