### ISSUE TITLE
qualitis0.9.1 , 从开发dag流程界面,点击qualitis后,获取不到project_id,是null,要在哪里进行排查呢？ 是因为这个项目的信息没有同步到qualitis中来?

### ISSUE THREAD

**Issue by xyh15864643181** [WeBankFinTech/Qualitis#129]
![image](https://user-images.githubusercontent.com/62532042/180903042-0f5839fc-779d-444c-990e-9f64cc54cbbe.png)

![image](https://user-images.githubusercontent.com/62532042/180903061-516c33f4-54e3-4cb2-a9f6-584461bad98f.png)

在服务器的linkis和dss qualitis都没有找到报错日志，问题文档给出的解决办法‘重建项目’也无法解决该问题

**Comment by Tangjiafeng** [comment]
重建项目后，可以在 Qualitis -- 我的项目 -- 工作流项目，查看是否同步创建了同名项目，如果还没有创建，需要优先排查项目同步创建接口的日志，定位问题并解决后，再进行页面节点的跳转。
