### ISSUE TITLE
qualitis 添加规则校验  无法选择库名表名

### ISSUE THREAD

**Issue by liusy-bd** [WeBankFinTech/Qualitis#131]
![image](https://user-images.githubusercontent.com/69708156/182573643-367a8c3e-5d1a-448d-a7d4-da445122bcf5.png)
![064c288fb1252332c982e214ad94f95](https://user-images.githubusercontent.com/69708156/182573861-d89968b4-0f54-4130-b06b-385be8dc12d1.jpg)
![0793172c9122bb1ec1751cee956a83c](https://user-images.githubusercontent.com/69708156/182573884-b9d08621-b537-4167-960c-64cd5cdebdda.jpg)

xiang'm项目制定规则 无法选择库名 表名
linkis  data-source-manager  也没报错

**Comment by liusy-bd** [comment]
![image](https://user-images.githubusercontent.com/69708156/182574549-e9e3a085-4291-4fdd-a353-8bf254ed3eb4.png)

linkis 测试数据源是ok的

**Comment by figodeng** [comment]
我也有相同的问题，通过linkis添加的数据源，在qualitis找不到。
linkis数据源：api/rest_j/v1/data-source-manager/info
qualitis查找linkis数据源：api/rest_j/v1/datasource/dbs

不确定是不是目前qualitis接入hive的database无法包含linkis的数据源，有两个疑问
1. 在linkis创建数据源的时候，是否会再hive中创建db
2. 是否会通过create external table的方式在hive穿件对应的table，否则通过接口api/rest_j/v1/datasource/tables?database=default如何查到对应的表

**Comment by KangTomwk** [comment]
hi，我也遇到相同问题，你解决了吗

**Comment by LordHL** [comment]
请问你们这个问题怎么处理的呀，我也遇到此问题了。

**Comment by figodeng** [comment]
Linkis最新版本部分API已经改动，Qualitis还没有update，检查一下两者的版本是否匹配，否则需要修改Qualitis的配置文件的API路径

**Comment by risebeforeshining** [comment]
我在配hive数据源的时候报错。然后datasource-manager报错
![image](https://user-images.githubusercontent.com/44262356/209933220-6d7adc66-8393-48ff-a6b4-ee84519cda0b.png)
导致我hive数据源配不上，楼上大佬怎么配的啊

**Comment by yemengisyou** [comment]
> hi，我也遇到相同问题，你解决了吗
你好，请查看系统设置中的linkis的地址写对着没，我的是没有写http://

**Comment by yemengisyou** [comment]
> > hi，我也遇到相同问题，你解决了吗
> > 你好，请查看系统设置中的linkis的地址写对着没，我的是没有写http://

一半情况都是配置上的错误

**Comment by Tangjiafeng** [comment]
当前这个版本仅支持 Hive 接口，不支持 Linkis 的数据源在 Qualitis 中使用。
