### ISSUE TITLE
打包异常，无相关版本依赖

### ISSUE THREAD

**Issue by xiangHannibal** [WeBankFinTech/Qualitis#132]
gradle4.6
centos7
Qualitis 0.9

![image](https://user-images.githubusercontent.com/6896623/182789099-1244bd19-6650-4ec4-b5a3-d52060edd844.png)

**Comment by utopianet** [comment]
可以到以下地址下载，手工放到对应本地仓库即可。
https://github.com/WeBankFinTech/Qualitis/releases/download/release-0.9.1/forgerock.zip
