### ISSUE TITLE
出不来HIVE源

### ISSUE THREAD

**Issue by NXL333** [WeBankFinTech/Qualitis#135]
![image](https://user-images.githubusercontent.com/62203971/184875104-b1b849c5-54e3-40b4-ba6c-cfeb4182d5ce.png)
![image](https://user-images.githubusercontent.com/62203971/184875171-eff275da-f3f4-4c25-9950-33efd44d7b26.png)

**Comment by jasonmrliu** [comment]
修改一下linkis-ps-publicservice.properties配置文件中linkis.metadata.hive.permission.with-login-user-enabled=false，否则Hive数据出不来

**Comment by figodeng** [comment]
会根据当前登录用户名过滤，保证qualitis登录用户和hive数据源创建用户一致

**Comment by Tangjiafeng** [comment]
这里的数据源暂时是屏蔽的，仅支持 Hive 数据的校验。
