### ISSUE TITLE
 start脚本里面有需要执行 qualitis  但是 bin目录下 没有这个脚本

### ISSUE THREAD

**Issue by zpandasoft** [WeBankFinTech/Qualitis#139]
**Describe the bug**
![image](https://user-images.githubusercontent.com/20449570/191192786-e8a829e8-0b8c-41be-81b7-c978e448a1b1.png)
如图 start.sh里面有需要执行qualitis ,但bin目录下没有此脚本
如需正常启动的话改怎么或者或者生成此脚本

**Comment by leiwangouc** [comment]
直接执行 QualitisServer 这个类
