### ISSUE TITLE
run rule exception

### ISSUE THREAD

**Issue by AllenJW** [WeBankFinTech/Qualitis#14]
![image](https://user-images.githubusercontent.com/22511490/70766624-43a04480-1d99-11ea-9659-dffcea98f10c.png)
![image](https://user-images.githubusercontent.com/22511490/70766658-5c105f00-1d99-11ea-9e83-69bd9adea0ef.png)
when run rules, cause 404 exception

**Comment by AllenJW** [comment]
the detail error follows
2019-12-13 11:11:22,615 ERROR [qtp1440325059-19] impl.OuterExecutionServiceImpl submitRules: I/O error on POST request for "http://xxxxx:9001/api/rest_j/v1/entrance/execute": 404 Not Found; nested exception is com.webank.wedatasphere.qualitis.exception.HttpRestTemplateException: 404 Not Found
org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://xxxxx:9001/api/rest_j/v1/entrance/execute": 404 Not Found; nested exception is com.webank.wedatasphere.qualitis.exception.HttpRestTemplateException: 404 Not Found

**Comment by howeye** [comment]
Open Eruaka of Linkis and confirm that Linkis is working well in this ip and port.

**Comment by AllenJW** [comment]
![image](https://user-images.githubusercontent.com/22511490/70773814-69d2de00-1db3-11ea-966f-c4c0a27ca8b7.png)

**Comment by howeye** [comment]
What about the log in gateway, is there any error in it?

**Comment by AllenJW** [comment]
![image](https://user-images.githubusercontent.com/22511490/70774074-275dd100-1db4-11ea-94d5-00d7c0795c97.png)
where are the detail errors

**Comment by howeye** [comment]
In "$LINKIS_HOME/linkis-gateway/logs"

**Comment by Tangjiafeng** [comment]
Recommend you to use the new version of Qualitis.
