### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by qq122356** [WeBankFinTech/Qualitis#144]
[Qualitis] version 0.9.2
gradle version 4.6

complie command  :  gradle clean distZip
error as follow

-------------------------------------------------------------------------------------
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':web/user:compileClasspath'.
> Could not find org.forgerock.opendj:opendj-core:3.0.0-SNAPSHOT.
  Searched in the following locations:
      file:/home/hadoop/.m2/repository/org/forgerock/opendj/opendj-core/3.0.0-SNAPSHOT/maven-metadata.xml
      file:/home/hadoop/.m2/repository/org/forgerock/opendj/opendj-core/3.0.0-SNAPSHOT/opendj-core-3.0.0-SNAPSHOT.pom
      file:/home/hadoop/.m2/repository/org/forgerock/opendj/opendj-core/3.0.0-SNAPSHOT/opendj-core-3.0.0-SNAPSHOT.jar
      http://maven.aliyun.com/nexus/content/groups/public/org/forgerock/opendj/opendj-core/3.0.0-SNAPSHOT/maven-metadata.xml
      http://maven.aliyun.com/nexus/content/groups/public/org/forgerock/opendj/opendj-core/3.0.0-SNAPSHOT/opendj-core-3.0.0-SNAPSHOT.pom
      http://maven.aliyun.com/nexus/content/groups/public/org/forgerock/opendj/opendj-core/3.0.0-SNAPSHOT/opendj-core-3.0.0-SNAPSHOT.jar
  Required by:
      project :web/user
> Could not find org.forgerock.opendj:opendj-grizzly:3.0.0-SNAPSHOT.
  Searched in the following locations:
      file:/home/hadoop/.m2/repository/org/forgerock/opendj/opendj-grizzly/3.0.0-SNAPSHOT/maven-metadata.xml
      file:/home/hadoop/.m2/repository/org/forgerock/opendj/opendj-grizzly/3.0.0-SNAPSHOT/opendj-grizzly-3.0.0-SNAPSHOT.pom
      file:/home/hadoop/.m2/repository/org/forgerock/opendj/opendj-grizzly/3.0.0-SNAPSHOT/opendj-grizzly-3.0.0-SNAPSHOT.jar
      http://maven.aliyun.com/nexus/content/groups/public/org/forgerock/opendj/opendj-grizzly/3.0.0-SNAPSHOT/maven-metadata.xml
      http://maven.aliyun.com/nexus/content/groups/public/org/forgerock/opendj/opendj-grizzly/3.0.0-SNAPSHOT/opendj-grizzly-3.0.0-SNAPSHOT.pom
      http://maven.aliyun.com/nexus/content/groups/public/org/forgerock/opendj/opendj-grizzly/3.0.0-SNAPSHOT/opendj-grizzly-3.0.0-SNAPSHOT.jar
  Required by:
      project :web/user
> Could not find org.forgerock.commons:forgerock-util:2.0.0-SNAPSHOT.
  Searched in the following locations:
      file:/home/hadoop/.m2/repository/org/forgerock/commons/forgerock-util/2.0.0-SNAPSHOT/maven-metadata.xml
      file:/home/hadoop/.m2/repository/org/forgerock/commons/forgerock-util/2.0.0-SNAPSHOT/forgerock-util-2.0.0-SNAPSHOT.pom
      file:/home/hadoop/.m2/repository/org/forgerock/commons/forgerock-util/2.0.0-SNAPSHOT/forgerock-util-2.0.0-SNAPSHOT.jar
      http://maven.aliyun.com/nexus/content/groups/public/org/forgerock/commons/forgerock-util/2.0.0-SNAPSHOT/maven-metadata.xml
      http://maven.aliyun.com/nexus/content/groups/public/org/forgerock/commons/forgerock-util/2.0.0-SNAPSHOT/forgerock-util-2.0.0-SNAPSHOT.pom
      http://maven.aliyun.com/nexus/content/groups/public/org/forgerock/commons/forgerock-util/2.0.0-SNAPSHOT/forgerock-util-2.0.0-SNAPSHOT.jar
  Required by:
      project :web/user
> Could not find org.forgerock.commons:i18n-core:1.4.2-SNAPSHOT.
  Searched in the following locations:
      file:/home/hadoop/.m2/repository/org/forgerock/commons/i18n-core/1.4.2-SNAPSHOT/maven-metadata.xml
      file:/home/hadoop/.m2/repository/org/forgerock/commons/i18n-core/1.4.2-SNAPSHOT/i18n-core-1.4.2-SNAPSHOT.pom
      file:/home/hadoop/.m2/repository/org/forgerock/commons/i18n-core/1.4.2-SNAPSHOT/i18n-core-1.4.2-SNAPSHOT.jar
      http://maven.aliyun.com/nexus/content/groups/public/org/forgerock/commons/i18n-core/1.4.2-SNAPSHOT/maven-metadata.xml
      http://maven.aliyun.com/nexus/content/groups/public/org/forgerock/commons/i18n-core/1.4.2-SNAPSHOT/i18n-core-1.4.2-SNAPSHOT.pom
      http://maven.aliyun.com/nexus/content/groups/public/org/forgerock/commons/i18n-core/1.4.2-SNAPSHOT/i18n-core-1.4.2-SNAPSHOT.jar
  Required by:
      project :web/user
> Could not find org.forgerock.commons:i18n-slf4j:1.4.2-SNAPSHOT.
  Searched in the following locations:
      file:/home/hadoop/.m2/repository/org/forgerock/commons/i18n-slf4j/1.4.2-SNAPSHOT/maven-metadata.xml
      file:/home/hadoop/.m2/repository/org/forgerock/commons/i18n-slf4j/1.4.2-SNAPSHOT/i18n-slf4j-1.4.2-SNAPSHOT.pom
      file:/home/hadoop/.m2/repository/org/forgerock/commons/i18n-slf4j/1.4.2-SNAPSHOT/i18n-slf4j-1.4.2-SNAPSHOT.jar
      http://maven.aliyun.com/nexus/content/groups/public/org/forgerock/commons/i18n-slf4j/1.4.2-SNAPSHOT/maven-metadata.xml
      http://maven.aliyun.com/nexus/content/groups/public/org/forgerock/commons/i18n-slf4j/1.4.2-SNAPSHOT/i18n-slf4j-1.4.2-SNAPSHOT.pom
      http://maven.aliyun.com/nexus/content/groups/public/org/forgerock/commons/i18n-slf4j/1.4.2-SNAPSHOT/i18n-slf4j-1.4.2-SNAPSHOT.jar
  Required by:
      project :web/user

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2m 10s
55 actionable tasks: 46 executed, 9 up-to-date

**Comment by v-wx-v** [comment]
提供org.springframework.boot:spring-boot-starter-data-jpa:2.0.4.RELEASE的依赖压缩包forgerock.zip，在本地.m2\repository\org解压，解决代码仓库拉取不到的问题。


please see  https://github.com/WeBankFinTech/Qualitis/releases

**Comment by XXwhite** [comment]
> 

这步有跟详细的说明吗
