### ISSUE TITLE
0.6.0qualitis how to update hive metadata?

### ISSUE THREAD

**Issue by AllenJW** [WeBankFinTech/Qualitis#15]
**Describe the bug**
![image](https://user-images.githubusercontent.com/22511490/70774241-95a29380-1db4-11ea-9513-cb425f3d02fc.png)
i added one cdh cluster, then i create rule, but i did not see the detail databases and tables about hive, how to update metadata, the 0.5.0version has one moudle of metadata management

**Comment by howeye** [comment]
In 0.6.0 version, meta data management is based on linkis, which will display all metadata that the user has when creating rules.

The question may be there is no any select privilege of user "admin" in your cluster. 
Please try to create a new user or modify the  username of "admin" to a user that has select privilege to database or table.

**Comment by AllenJW** [comment]
![image](https://user-images.githubusercontent.com/22511490/70775907-a522dc00-1db6-11ea-9509-6c8ffa9295e9.png)
Another username admin_test has the same problem

**Comment by howeye** [comment]
Is "admin_test" has any select privilege on database or table in your cluster?

**Comment by AllenJW** [comment]
where to grant select privilege to admin_test, the privilege i grant as folows
![image](https://user-images.githubusercontent.com/22511490/70776540-4bbbac80-1db8-11ea-81a3-db4a994045fd.png)
![image](https://user-images.githubusercontent.com/22511490/70776560-5d04b900-1db8-11ea-8cab-27490a1e9d47.png)
it looks like hive the same privilege as admin user

**Comment by howeye** [comment]
Grant privilege in hive to you user.

**Comment by AllenJW** [comment]
The user admin_test is in qualitis, how to Grant privilege in hive.  A little disorganized !!

**Comment by howeye** [comment]
Which user do you have in hive? Create it in Qualitis and you can choose database and table in qualitis.
