### ISSUE TITLE
本地编译，使用gradle4.6，qualitis 0.9.2版本，执行gradle clean build 失败

### ISSUE THREAD

**Issue by LordHL** [WeBankFinTech/Qualitis#151]
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':web/user:compileClasspath'.
> Could not find org.forgerock.opendj:opendj-core:3.0.0-SNAPSHOT.
  Searched in the following locations:
      https://maven.aliyun.com/repository/public/org/forgerock/opendj/opendj-core/3.0.0-SNAPSHOT/maven-metadata.xml
      https://maven.aliyun.com/repository/public/org/forgerock/opendj/opendj-core/3.0.0-SNAPSHOT/opendj-core-3.0.0-SNAPSHOT.pom
      https://maven.aliyun.com/repository/public/org/forgerock/opendj/opendj-core/3.0.0-SNAPSHOT/opendj-core-3.0.0-SNAPSHOT.jar
      file:/C:/Users/willi/.m2/repository/org/forgerock/opendj/opendj-core/3.0.0-SNAPSHOT/maven-metadata.xml
      file:/C:/Users/willi/.m2/repository/org/forgerock/opendj/opendj-core/3.0.0-SNAPSHOT/opendj-core-3.0.0-SNAPSHOT.pom
      file:/C:/Users/willi/.m2/repository/org/forgerock/opendj/opendj-core/3.0.0-SNAPSHOT/opendj-core-3.0.0-SNAPSHOT.jar
      https://repo.maven.apache.org/maven2/org/forgerock/opendj/opendj-core/3.0.0-SNAPSHOT/maven-metadata.xml
      https://repo.maven.apache.org/maven2/org/forgerock/opendj/opendj-core/3.0.0-SNAPSHOT/opendj-core-3.0.0-SNAPSHOT.pom
      https://repo.maven.apache.org/maven2/org/forgerock/opendj/opendj-core/3.0.0-SNAPSHOT/opendj-core-3.0.0-SNAPSHOT.jar
      http://maven.aliyun.com/nexus/content/groups/public/org/forgerock/opendj/opendj-core/3.0.0-SNAPSHOT/maven-metadata.xml
      http://maven.aliyun.com/nexus/content/groups/public/org/forgerock/opendj/opendj-core/3.0.0-SNAPSHOT/opendj-core-3.0.0-SNAPSHOT.pom
      http://maven.aliyun.com/nexus/content/groups/public/org/forgerock/opendj/opendj-core/3.0.0-SNAPSHOT/opendj-core-3.0.0-SNAPSHOT.jar
  Required by:
      project :web/user
> Could not find org.forgerock.opendj:opendj-grizzly:3.0.0-SNAPSHOT.
  Searched in the following locations:
      https://maven.aliyun.com/repository/public/org/forgerock/opendj/opendj-grizzly/3.0.0-SNAPSHOT/maven-metadata.xml
      https://maven.aliyun.com/repository/public/org/forgerock/opendj/opendj-grizzly/3.0.0-SNAPSHOT/opendj-grizzly-3.0.0-SNAPSHOT.pom
      https://maven.aliyun.com/repository/public/org/forgerock/opendj/opendj-grizzly/3.0.0-SNAPSHOT/opendj-grizzly-3.0.0-SNAPSHOT.jar
      file:/C:/Users/willi/.m2/repository/org/forgerock/opendj/opendj-grizzly/3.0.0-SNAPSHOT/maven-metadata.xml
      file:/C:/Users/willi/.m2/repository/org/forgerock/opendj/opendj-grizzly/3.0.0-SNAPSHOT/opendj-grizzly-3.0.0-SNAPSHOT.pom
      file:/C:/Users/willi/.m2/repository/org/forgerock/opendj/opendj-grizzly/3.0.0-SNAPSHOT/opendj-grizzly-3.0.0-SNAPSHOT.jar
      https://repo.maven.apache.org/maven2/org/forgerock/opendj/opendj-grizzly/3.0.0-SNAPSHOT/maven-metadata.xml
      https://repo.maven.apache.org/maven2/org/forgerock/opendj/opendj-grizzly/3.0.0-SNAPSHOT/opendj-grizzly-3.0.0-SNAPSHOT.pom
      https://repo.maven.apache.org/maven2/org/forgerock/opendj/opendj-grizzly/3.0.0-SNAPSHOT/opendj-grizzly-3.0.0-SNAPSHOT.jar
      http://maven.aliyun.com/nexus/content/groups/public/org/forgerock/opendj/opendj-grizzly/3.0.0-SNAPSHOT/maven-metadata.xml
      http://maven.aliyun.com/nexus/content/groups/public/org/forgerock/opendj/opendj-grizzly/3.0.0-SNAPSHOT/opendj-grizzly-3.0.0-SNAPSHOT.pom
      http://maven.aliyun.com/nexus/content/groups/public/org/forgerock/opendj/opendj-grizzly/3.0.0-SNAPSHOT/opendj-grizzly-3.0.0-SNAPSHOT.jar
  Required by:
      project :web/user
> Could not find org.forgerock.commons:forgerock-util:2.0.0-SNAPSHOT.
  Searched in the following locations:
      https://maven.aliyun.com/repository/public/org/forgerock/commons/forgerock-util/2.0.0-SNAPSHOT/maven-metadata.xml
      https://maven.aliyun.com/repository/public/org/forgerock/commons/forgerock-util/2.0.0-SNAPSHOT/forgerock-util-2.0.0-SNAPSHOT.pom
      https://maven.aliyun.com/repository/public/org/forgerock/commons/forgerock-util/2.0.0-SNAPSHOT/forgerock-util-2.0.0-SNAPSHOT.jar
      file:/C:/Users/willi/.m2/repository/org/forgerock/commons/forgerock-util/2.0.0-SNAPSHOT/maven-metadata.xml
      file:/C:/Users/willi/.m2/repository/org/forgerock/commons/forgerock-util/2.0.0-SNAPSHOT/forgerock-util-2.0.0-SNAPSHOT.pom
      file:/C:/Users/willi/.m2/repository/org/forgerock/commons/forgerock-util/2.0.0-SNAPSHOT/forgerock-util-2.0.0-SNAPSHOT.jar
      https://repo.maven.apache.org/maven2/org/forgerock/commons/forgerock-util/2.0.0-SNAPSHOT/maven-metadata.xml
      https://repo.maven.apache.org/maven2/org/forgerock/commons/forgerock-util/2.0.0-SNAPSHOT/forgerock-util-2.0.0-SNAPSHOT.pom
      https://repo.maven.apache.org/maven2/org/forgerock/commons/forgerock-util/2.0.0-SNAPSHOT/forgerock-util-2.0.0-SNAPSHOT.jar
      http://maven.aliyun.com/nexus/content/groups/public/org/forgerock/commons/forgerock-util/2.0.0-SNAPSHOT/maven-metadata.xml
      http://maven.aliyun.com/nexus/content/groups/public/org/forgerock/commons/forgerock-util/2.0.0-SNAPSHOT/forgerock-util-2.0.0-SNAPSHOT.pom
      http://maven.aliyun.com/nexus/content/groups/public/org/forgerock/commons/forgerock-util/2.0.0-SNAPSHOT/forgerock-util-2.0.0-SNAPSHOT.jar
  Required by:
      project :web/user
> Could not find org.forgerock.commons:i18n-core:1.4.2-SNAPSHOT.
  Searched in the following locations:
      https://maven.aliyun.com/repository/public/org/forgerock/commons/i18n-core/1.4.2-SNAPSHOT/maven-metadata.xml
      https://maven.aliyun.com/repository/public/org/forgerock/commons/i18n-core/1.4.2-SNAPSHOT/i18n-core-1.4.2-SNAPSHOT.pom
      https://maven.aliyun.com/repository/public/org/forgerock/commons/i18n-core/1.4.2-SNAPSHOT/i18n-core-1.4.2-SNAPSHOT.jar
      file:/C:/Users/willi/.m2/repository/org/forgerock/commons/i18n-core/1.4.2-SNAPSHOT/maven-metadata.xml
      file:/C:/Users/willi/.m2/repository/org/forgerock/commons/i18n-core/1.4.2-SNAPSHOT/i18n-core-1.4.2-SNAPSHOT.pom
      file:/C:/Users/willi/.m2/repository/org/forgerock/commons/i18n-core/1.4.2-SNAPSHOT/i18n-core-1.4.2-SNAPSHOT.jar
      https://repo.maven.apache.org/maven2/org/forgerock/commons/i18n-core/1.4.2-SNAPSHOT/maven-metadata.xml
      https://repo.maven.apache.org/maven2/org/forgerock/commons/i18n-core/1.4.2-SNAPSHOT/i18n-core-1.4.2-SNAPSHOT.pom
      https://repo.maven.apache.org/maven2/org/forgerock/commons/i18n-core/1.4.2-SNAPSHOT/i18n-core-1.4.2-SNAPSHOT.jar
      http://maven.aliyun.com/nexus/content/groups/public/org/forgerock/commons/i18n-core/1.4.2-SNAPSHOT/maven-metadata.xml
      http://maven.aliyun.com/nexus/content/groups/public/org/forgerock/commons/i18n-core/1.4.2-SNAPSHOT/i18n-core-1.4.2-SNAPSHOT.pom
      http://maven.aliyun.com/nexus/content/groups/public/org/forgerock/commons/i18n-core/1.4.2-SNAPSHOT/i18n-core-1.4.2-SNAPSHOT.jar
  Required by:
      project :web/user
> Could not find org.forgerock.commons:i18n-slf4j:1.4.2-SNAPSHOT.
  Searched in the following locations:
      https://maven.aliyun.com/repository/public/org/forgerock/commons/i18n-slf4j/1.4.2-SNAPSHOT/maven-metadata.xml
      https://maven.aliyun.com/repository/public/org/forgerock/commons/i18n-slf4j/1.4.2-SNAPSHOT/i18n-slf4j-1.4.2-SNAPSHOT.pom
      https://maven.aliyun.com/repository/public/org/forgerock/commons/i18n-slf4j/1.4.2-SNAPSHOT/i18n-slf4j-1.4.2-SNAPSHOT.jar
      file:/C:/Users/willi/.m2/repository/org/forgerock/commons/i18n-slf4j/1.4.2-SNAPSHOT/maven-metadata.xml
      file:/C:/Users/willi/.m2/repository/org/forgerock/commons/i18n-slf4j/1.4.2-SNAPSHOT/i18n-slf4j-1.4.2-SNAPSHOT.pom
      file:/C:/Users/willi/.m2/repository/org/forgerock/commons/i18n-slf4j/1.4.2-SNAPSHOT/i18n-slf4j-1.4.2-SNAPSHOT.jar
      https://repo.maven.apache.org/maven2/org/forgerock/commons/i18n-slf4j/1.4.2-SNAPSHOT/maven-metadata.xml
      https://repo.maven.apache.org/maven2/org/forgerock/commons/i18n-slf4j/1.4.2-SNAPSHOT/i18n-slf4j-1.4.2-SNAPSHOT.pom
      https://repo.maven.apache.org/maven2/org/forgerock/commons/i18n-slf4j/1.4.2-SNAPSHOT/i18n-slf4j-1.4.2-SNAPSHOT.jar
      http://maven.aliyun.com/nexus/content/groups/public/org/forgerock/commons/i18n-slf4j/1.4.2-SNAPSHOT/maven-metadata.xml
      http://maven.aliyun.com/nexus/content/groups/public/org/forgerock/commons/i18n-slf4j/1.4.2-SNAPSHOT/i18n-slf4j-1.4.2-SNAPSHOT.pom
      http://maven.aliyun.com/nexus/content/groups/public/org/forgerock/commons/i18n-slf4j/1.4.2-SNAPSHOT/i18n-slf4j-1.4.2-SNAPSHOT.jar
  Required by:
      project :web/user

对应的包，在maven中央仓库找不到对应版本的包，而且这些包都是快照版本的，建议改成文档版本的

**Comment by RUIzg** [comment]
为 什么这个 issue被关闭了，我现在编译也遇到这个问题了
