### ISSUE TITLE
Failed to get database(获取数据库失败)

### ISSUE THREAD

**Issue by risebeforeshining** [WeBankFinTech/Qualitis#152]
**Describe the bug**
When adding new rules on the web page, an error emerged;  "=Failed to get database(获取数据库失败)"
在添加规则页面，显示获取数据库失败。
The logs prints: 
![1671588054416](https://user-images.githubusercontent.com/44262356/208803989-2914aaa7-fbf1-454c-80a1-e2c735f50e36.jpg)
It said that there's error obtaining JDBC connection. The property "useUnicode" got the wrong parameter. 
日志打印：useUnicode输入参数错误。

**To Reproduce**
It is because of the linkis, right? I reviewed the configuration of linkis 1.1.1,  but didn't find where this wrong format parameter comes from;
报错原因是因为linkis嘛？我看了linkis1.1.1的配置，没有找到这一块的信息，这个错是在哪里配的啊？  

**Desktop (please complete the following information):**
 - OS: centOS7
 - Browser: chrome
 - Qualitis: 0.9.2
 - Linkis: 1.1.1

**Comment by Tangjiafeng** [comment]
这里是 Linkis 的元数据接口，也就是获取库列表，表列表，字段列表，可以检查 Linkis 元数据服务是否正常，已经你在 Qualitis 侧配置的 Linkis 集群地址和 Token 是否正确。
