### ISSUE TITLE
qualitis:test: Could not find org.forgerock.opendj:opendj-core:3.0.0-SNAPSHOT.

### ISSUE THREAD

**Issue by netcloudtec** [WeBankFinTech/Qualitis#154]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alexzhu0592** [comment]
可以参考pr里面有一个解决办法，这个依赖的中央仓库的group-id有变化 (build(gradle): upgrade gradle to 7.5 #136)
