### ISSUE TITLE
关系型数据库质量分析

### ISSUE THREAD

**Issue by isushao** [WeBankFinTech/Qualitis#155]
Linkis 1.3.0
Qualitis 0.9.2

![image](https://user-images.githubusercontent.com/16602760/218401994-8f0f87d0-3b14-4343-9748-9807fa41356e.png)

请问，已经支持的关系型数据库源如何使用？

**Comment by jiaojinnaozhixiangmingzi** [comment]
同问，新增的这些功能有没有用户手册，部署后找不到入口
