### ISSUE TITLE
本地启动quanlitis项目乱码

### ISSUE THREAD

**Issue by rainbowJson** [WeBankFinTech/Qualitis#156]
![QQ截图20230220101701](https://user-images.githubusercontent.com/12165006/219994481-83ecb76e-63da-4331-b066-440e10baf5fe.jpg)
本地启动时候图标乱码，请问怎么解决呢？

**Comment by jiaojinnaozhixiangmingzi** [comment]
同问

**Comment by zhangsan20161111** [comment]
在idea -> 找到Help ->  点击Edit Custom VM Options... 在idea64.exe.vmoptions文件中加入 -Dfile.encoding=UTF-8，最后重启idea

**Comment by Tangjiafeng** [comment]
可以使用 1.0.0 版本，或者另外检查数据库的编码是否是 UTF-8，前端代码编译包是否在 UTF-8 环境下进行。
