### ISSUE TITLE
发现qualitis  application-dev.yaml里面接口没有

### ISSUE THREAD

**Issue by rainbowJson** [WeBankFinTech/Qualitis#157]
meta_data:
      datasource_connect_param: data-source-manager/{DATA_SOURCE_ID}/connect_params

请问此处是否是配置错误

**Comment by wangxx210** [comment]
应该是这样的

**Comment by wangxx210** [comment]
应该是这样的
datasource_connect_param: data-source-manager/{DATA_SOURCE_ID}/connect-params
