### ISSUE TITLE
调用linkis获取字段信息报错

### ISSUE THREAD

**Issue by rainbowJson** [WeBankFinTech/Qualitis#158]
Unable to fetch table jwwl_cc_in_storage_main. Your client does not appear to support insert-only tables. To skip capability checks, please set metastore.client.capability.check to false. This setting can be set globally, or on the client for the current metastore session. Note that this may lead to incorrect results, data loss, undefined behavior, etc. if your client is actually incompatible. You can also specify custom client capabilities via get_table_req API.

linkis接口:  api/rest_j/v1/metadatamanager/columns/1/db/test/table/jwwl_cc_in_storage_main?system=Qualitis

**Comment by Tangjiafeng** [comment]
这看起来是 mysql 数据源的字段获取接口，可以优先检查 Linkis 数据源服务，元数据查询模块是否正常，test.jwwl_cc_in_storage_main 这个库表是否存在。
