### ISSUE TITLE
How can I choose the table which does not exist when I edit the qualitis rule?

### ISSUE THREAD

**Issue by yangzhiyue** [WeBankFinTech/Qualitis#16]
When I edited a workflow, for example,  qualitis node is after spark node, I use spark to create a new table, AAA as an exmaple, I wanna to check this AAA table's quality , but I cannot choose this table  in editing page? Can I just input the table name?

**Comment by howeye** [comment]
Because the table is not exist when you edit the qualitis node, so you can't choose it in template rule.
However, you can type the table in the custom rule, which should satisfy your demand.
