### ISSUE TITLE
本地gradle编译0.9.2 ErrorCustomController.java:27: 错误: 方法不会覆盖或实现 超类型的方法

### ISSUE THREAD

**Issue by Tiger-ygq** [WeBankFinTech/Qualitis#172]
![image](https://github.com/WeBankFinTech/Qualitis/assets/68222312/2e3c1cc3-54f1-44f2-b327-65c4ab62a22c)
![image](https://github.com/WeBankFinTech/Qualitis/assets/68222312/2c9a5979-b938-4aac-95c1-b439dd98ebe4)

**Comment by Tangjiafeng** [comment]
可以移除，或升级使用 1.0.0。
