### ISSUE TITLE
Qualitis执行任务超时

### ISSUE THREAD

**Issue by guanym98k** [WeBankFinTech/Qualitis#173]
Linkis1.4.0版本，Qualitis执行任务超时，Linkis的6个服务都有正常启动，有大佬知道我该排查哪里吗，报错信息：
desc: Waiting for engineNode:AMEngineNode{nodeStatus=null, lock='null', serviceInstance=ServiceInstance(linkis-cg-engineconn, ks-jenkins-04:46682), owner='admin'}(8876b001-1212-4891-84e6-9f6c3042add9) initialization TimeoutException, already waiting 657986 ms
![image](https://github.com/WeBankFinTech/Qualitis/assets/36252056/5ebd7860-728c-481b-aa71-e9abea175bac)
![f5880f43d8dfdf2d26e8abc2216962d](https://github.com/WeBankFinTech/Qualitis/assets/36252056/ad648366-8b60-43c7-bcea-a72a11ee3748)

**Comment by jjlujunjian** [comment]
我遇到了这个问题，后续就一直卡在那里了
![image](https://github.com/WeBankFinTech/Qualitis/assets/5919340/3fb2b5df-9170-4e37-86a2-43bd8ad83b4e)

**Comment by guanym98k** [comment]
> 我遇到了这个问题，后续就一直卡在那里了 ![image](https://user-images.githubusercontent.com/5919340/277931747-3fb2b5df-9170-4e37-86a2-43bd8ad83b4e.png)

搞了几天，一直卡在这里，很难受，报错信息，就是超时重试

**Comment by guanym98k** [comment]
报错信息如下，现在还没有解决
2023-10-26 12:16:59.016 INFO This TaskID_29_otJobId_astJob_0_codeExec_0 retry, new retry-task is:TaskID_29_otJobId_astJob_0_retry_0, retryCount: 1.reason:ask Engine failed errCode: 12003 ,desc: localhost.hiveserver:9101_1 Failed  to async get EngineNode Asynchronous request engine timeout(请求引擎超时，可能是因为资源不足，您可以选择重试),async id localhost.hiveserver:9101_1 ,ip: localhost.hiveserver ,port: 9104 ,serviceKind: linkis-cg-entrance

**Comment by guanym98k** [comment]
问题已解决，重新搭了一遍linkis然后执行linkis cli就可以了，可以先尝试执行下简单的，如：sh ./bin/linkis-cli -engineType shell-1 -codeType shell -code "echo \"hello\" " -submitUser root -proxyUser root
