### ISSUE TITLE
项目找不到接口 /qualitis/api/v1/redirect

### ISSUE THREAD

**Issue by yuanzhiwei** [WeBankFinTech/Qualitis#175]
**Describe the bug**

**To Reproduce**
1. 接入dss , iframe里边会请求qualitis的这个接口 , 但是请求不到, 我在项目中也找不到

**Desktop (please complete the following information):**
 - DSS 1.1.2
 - qualitis 0.9.2
 
![image](https://github.com/WeBankFinTech/Qualitis/assets/17841347/40f5a4c3-d4b8-43ff-b007-2a8fbfbd760c)

**Comment by Tangjiafeng** [comment]
需升级 1.0.0 版本。
