### ISSUE TITLE
编译报错Could not find org.forgerock.opendj:opendj-core:3.0.0-SNAPSHOT.

### ISSUE THREAD

**Issue by wangkun723** [WeBankFinTech/Qualitis#176]
![image](https://github.com/WeBankFinTech/Qualitis/assets/83483385/44401234-0a73-487f-b56e-fac5758c7e94)
查了maven库和阿里云的库都没有

**Comment by ypa23333** [comment]
但是这里面有pom和xml文件，编译还是报错
