### ISSUE TITLE
dss/bin执行appconn-install.sh，一直卡在第三步

### ISSUE THREAD

**Issue by wangkun723** [WeBankFinTech/Qualitis#177]
![image](https://github.com/WeBankFinTech/Qualitis/assets/83483385/4ad18b56-9193-4ef7-b5e6-4d9b7cfc358b)
Step3: load the plugin of qualitis AppConn in DSS.
Now try to call dss-server to reload the plugin of qualitis AppConn.
什么原因？

**Comment by Tangjiafeng** [comment]
请在这里提交 issue：https://github.com/WeBankFinTech/DataSphereStudio
