### ISSUE TITLE
branch-1.0.0编译成功、启动成功，但是无法访问

### ISSUE THREAD

**Issue by adonis-lau** [WeBankFinTech/Qualitis#181]
分支：branch-1.0.0
按照 branch-1.0.0/docs/zh_CN/ch1/快速搭建手册——单机.md 文档编译并修改配置之后，报错说获取不到 datasource_cluster 配置值（凡是 key = [value] 形式的都会报错），改之。
能够启动成功，浏览器中访问 http://127.0.0.1:8090/ ，页面显示

哎呀迷路了...
可能的原因：

路径不存在或已被删除
我们的服务器被外星人劫持了
[返回首页](http://127.0.0.1:8090/) [返回上一页](javascript:history.go(-1);)

日志报错：
2024-01-12 18:07:50,067 ERROR [http-nio-8090-exec-3] controller.ErrorCustomController handleError: error page

**Comment by shixiutao** [comment]
一样的问题

**Comment by ComeFromChina** [comment]
怎么解决的呢

**Comment by penny321** [comment]
都有这个问题呢。我是源码直接编译，web/app:test过不去，就忽略掉啦。再打包是没问题的，但是访问404，谁能给说一下吖

**Comment by shixiutao** [comment]
问了社区，这个问题解决掉了，1.0.0的前端需要单独编译放到static下，参考0.9.2的格式
npm -i
npm run build

**Comment by sunfeii** [comment]
@shixiutao 感谢提示，这个问题解决了！为后来人少走些弯路，我补充一下：在源码包的ui目录下，npm -i，npm run build，build出来的dist里面的东西，copy到qualitis-1.0.0（gradle编译出来后解压缩的）/conf/static下面。node版本不要太高，我用的14

**Comment by z-one-one** [comment]
node 版本12.13，提示'fes' 不是内部或外部命令

**Comment by Chris-Arith** [comment]
> @shixiutao 感谢提示，这个问题解决了！为后来人少走些弯路，我补充一下：在源码包的ui目录下，npm -i，npm run build，build出来的dist里面的东西，copy到qualitis-1.0.0（gradle编译出来后解压缩的）/conf/static下面。node版本不要太高，我用的14

编译时如果报错
```
> dqm-ui-next@1.1.0 prepare
> husky install

.git can't be found (see https://git.io/Jc3F9)
```
需要修改package.json文件，将` "prepare": "husky install"`修改为`"prepare": "cd .. && husky install web/.husky"`
