### ISSUE TITLE
工作流中打开qualitis组件失败

### ISSUE THREAD

**Issue by LostKe** [WeBankFinTech/Qualitis#183]
dss：1.4.0  qualitis：0.9.2

工作流中打开qualitis报404异常，debug代码发现 qualitis中使用dss-sso-integration-standard-1.1.0.jar#SSOPluginFilter#doFilter方法，方法中sendRedirect值为http://xxxx/#/projects/rules?workflowProject=true&tpl=......
上述 /project/rules接口在qualitis和dss项目中都未找到对应代码，是版本不匹配导致的吗

**Comment by Tangjiafeng** [comment]
需升级 1.0.0
