### ISSUE TITLE
求助：管理台-数据源管理-测试连接失败，日志报NullPointerException

### ISSUE THREAD

**Issue by xiexinyu1994** [WeBankFinTech/Qualitis#190]
qualitis版本：release-1.0.0
1.管理台连接数据源失败，请问大佬们知道啥原因吗？

**Comment by xiexinyu1994** [comment]
补充一下连接配置中点详情，然后点编辑直接展示的是下面这样，上面是我点击编辑后自己又重填了一遍，我怀疑这数据是不是没保存
<img width="624" alt="b6" src="https://github.com/WeBankFinTech/Qualitis/assets/54489979/73b4e303-ef53-45ab-863a-9c8fa1304274">

**Comment by DOVER123** [comment]
你这边部署了之后，登录有没有报500错误？

**Comment by xiexinyu1994** [comment]
> 你这边部署了之后，登录有没有报500错误？

没有，报了404，然后重新到源码包下编译一下把前端页面copy过去就好了

**Comment by Tangjiafeng** [comment]
先保存，再测试连接，同时发布，规则中才可使用。
