### ISSUE TITLE
1.0.0部署之后，登录不成功，500

### ISSUE THREAD

**Issue by DOVER123** [WeBankFinTech/Qualitis#191]
1.0.0 启动成功，页面也出来了，但是报500，并且输入ip也报500，得输入ip/index.html 首页才能出来。
后台报错截图如下
![image](https://github.com/WeBankFinTech/Qualitis/assets/17616876/fe015a06-cafd-42da-9258-9b03d01f631b)
有没有好心人帮忙看看咋回事

**Comment by Tangjiafeng** [comment]
首页是要 /index.html。
