### ISSUE TITLE
Failed to login with the predefined admin user and password

### ISSUE THREAD

**Issue by RainFlying** [WeBankFinTech/Qualitis#24]
In the log file I can see the following log message:

{"username":"admin","password":"8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"}

Checked the database, the hashed passwords are the same.

mysql> select password from qualitis_auth_user where username = 'admin';
+------------------------------------------------------------------+
| password                                                         |
+------------------------------------------------------------------+
| 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918 |
+------------------------------------------------------------------+
1 row in set (0.00 sec)

**Comment by Tangjiafeng** [comment]
It is necessary to check whether the admin's role and authority assignment is normal.
