### ISSUE TITLE
java.lang.ClassNotFoundException: org.apache.zookeeper.Watcher

### ISSUE THREAD

**Issue by jianghuzai** [WeBankFinTech/Qualitis#25]
**Describe the bug**
with zkCurator at 2.12.0, I will get the Exception( java.lang.ClassNotFoundException: org.apache.zookeeper.Watcher) when I start QualitisServer
but none Execption at 2.7.1

**To Reproduce**
1. just start QualitisServer

**Expected behavior**
Application run success

**Screenshots**
![image](https://user-images.githubusercontent.com/16590040/71540423-4a2be000-2985-11ea-988d-5a273359ced6.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.4
 - IDEA: 2019.2.4

**Additional context**
Application run success with zkCurator:2.7.1

**Comment by Tangjiafeng** [comment]
Please follow the special version of zkCurator in project dependency.
