### ISSUE TITLE
新建自定义规则后点确定报错

### ISSUE THREAD

**Issue by niepanchongsheng** [WeBankFinTech/Qualitis#26]
**Describe the bug**
新建自定义规则后点确定报错，web页面报错：request failed

**Screenshots**
![image](https://user-images.githubusercontent.com/19420345/71616885-7056b780-2bf3-11ea-956b-5d0ad0c80c08.png)
![image](https://user-images.githubusercontent.com/19420345/71616897-82d0f100-2bf3-11ea-9e9d-dfba62bae440.png)

**Desktop (please complete the following information):**
- OS: CentOS7
 - Version: Qualitis-0.7.0

**Comment by Tangjiafeng** [comment]
Recommend you to use the new version of Qualitis.
