### ISSUE TITLE
新增技术规则报错

### ISSUE THREAD

**Issue by Wf675721680** [WeBankFinTech/Qualitis#28]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
<img width="970" alt="截屏2020-02-07下午5 57 39" src="https://user-images.githubusercontent.com/57088544/74019906-6df63300-49d3-11ea-87d0-a5155488f4c8.png">
无法识别数据库信息
日志信息如下：
<img width="1359" alt="截屏2020-02-07下午6 01 35" src="https://user-images.githubusercontent.com/57088544/74020171-f4127980-49d3-11ea-94bf-bb30687825af.png">

**Additional context**

**Comment by Tangjiafeng** [comment]
Recommend you to use the new version of Qualitis.
