### ISSUE TITLE
无法引入文档生成工具swagger

### ISSUE THREAD

**Issue by wuchenxi123** [WeBankFinTech/Qualitis#31]
1.现象
引入swagger2.5.0以上版本，编译无法通过
![23731583319207_ pic_hd](https://user-images.githubusercontent.com/14171052/75936363-dfcf7880-5ebc-11ea-9929-66f8723d3f76.jpg)
2.猜测原因
jar包依赖问题
![191583134048_ pic_hd](https://user-images.githubusercontent.com/14171052/75936465-21602380-5ebd-11ea-881d-2301c267b0e7.jpg)
![121583133882_ pic](https://user-images.githubusercontent.com/14171052/75936492-3fc61f00-5ebd-11ea-804a-298cce6ee8e0.jpg)
ApiDocumentationScanner类引用的Multimaps是org.apache.hive:hive-exec里的，但是应该要引用的Multimaps其实是com.google.guava:guava
3.解决方案
1）升级org.apache.hive:hive-exec
2）指定ApiDocumentationScanner类里的正确引用，比较难实现，因为类Multimaps包的路径完全一样

**Comment by Tangjiafeng** [comment]
Please upgrade as appropriate for hive in an open source environment.
