### ISSUE TITLE
ui 乱码

### ISSUE THREAD

**Issue by smlHao** [WeBankFinTech/Qualitis#34]
Hi，在使用中发现以下小问题，希望帮解决下，谢谢

Qualitis的版本是0.6.0

在idea中引入源码启动登录后    访问界面出现部分乱码
![aab3b80b8e6ade018a93a6df5e553aa](https://user-images.githubusercontent.com/3837738/78009763-12617980-7374-11ea-95d7-d74f1e2de656.png)

gradle clean distZip 报错

![1585646690(1)](https://user-images.githubusercontent.com/3837738/78010123-94ea3900-7374-11ea-9552-2c0d752bbd6d.png)

**Comment by Tangjiafeng** [comment]
Recommend you to use the new version of Qualitis.

**Comment by figodeng** [comment]
最新版本本地调试依然是乱码，有没有哪个大佬有解决方案？

**Comment by tangzhanbo** [comment]
最新版本本地调试依然是乱码，有没有哪个大佬有解决方案？
