### ISSUE TITLE
Qualitis适配3.0.0-CDH6.1.0版本hadoop时编译异常

### ISSUE THREAD

**Issue by robinzyx** [WeBankFinTech/Qualitis#4]
**Describe the bug**
在适配3.0.0-CDH6.1.0版本hadoop，并进行编译时报如下错误：
`FAILURE: Build failed with an exception.
> :core/common:compileJava > Resolving dependencies ':core/common:compileClasspath'
* What went wrong:
Could not resolve all dependencies for configuration ':core/common:compileClasspath'.
> Could not determine artifacts for javax.ws.rs:javax.ws.rs-api:2.1
   > Could not get resource 'http://10.18.101.56:8081/repository/maven-public/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.$%7Bpackaging.type%7D'.
      > Could not HEAD 'http://10.18.101.56:8081/repository/maven-public/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.$%7Bpackaging.type%7D'. Received status code 400 from server: Invalid repository path

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 28.557 secs`

**Comment by howeye** [comment]
which gradle version do you use?

**Comment by robinzyx** [comment]
> which gradle version do you use?

gradle 3.5

**Comment by howeye** [comment]
Try changing gradle version to 4.9
