### ISSUE TITLE
Could not find com.webank.wedatasphere.dss:dss-appjoint-auth:0.9.0.WEBANK.

### ISSUE THREAD

**Issue by jitangpaochaomi** [WeBankFinTech/Qualitis#46]
maven仓库最新版为0.7.0，能否更新为0.9.0

**Comment by Tangjiafeng** [comment]
dss:dss-appjoint-auth:0.9.0.WEBANK need to local install dss source code.

**Comment by zjch12** [comment]
dss:dss-appjoint-auth:0.9.0.WEBANK  is not found，only dss:dss-appjoint-auth:0.9.0 found，and when i complie it ,I find the .jar file is unlike release version， I can''t find link-*.0.9.7.WEBANK.jar file
