### ISSUE TITLE
0.8.0 binary release version conflics with source code version

### ISSUE THREAD

**Issue by riddlegit** [WeBankFinTech/Qualitis#48]
**Describe the bug**
Unzip the 0.8.0 release binary package, you can see in lib directory, all core-*.jar files are marked with 0.9.0 version, at the same time unzip the 0.8.0 source package, rebuild it and the jar file in build directories all marked with 0.8.0 version, this makes a little confuse, can any one explain how to match the source code and binary of 0.8.0 version?

**To Reproduce**

**Expected behavior**

**Screenshots**
![图片](https://user-images.githubusercontent.com/4182168/112413967-290a9880-8d5c-11eb-81a8-099afc282027.png)
![图片](https://user-images.githubusercontent.com/4182168/112414237-af26df00-8d5c-11eb-819a-6fa4b3c83570.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Tangjiafeng** [comment]
Because of the gradle.properties error version number, you can modify it to 0.8.0 and gradle install.
