### ISSUE TITLE
When to support mysql、clickhouse

### ISSUE THREAD

**Issue by chenjie4106** [WeBankFinTech/Qualitis#49]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Tangjiafeng** [comment]
Waiting for the data source management of linkis to go online, qualitis can support

**Comment by marxy** [comment]
I found that the master of linkis supports the datasource management.I cant't wait qualitis to support it.
