### ISSUE TITLE
fes.js has been open sourced. 

### ISSUE THREAD

**Issue by liangjun-jiang** [WeBankFinTech/Qualitis#51]
**Describe the bug**
The README.md said `fes.js` is not open sourced but I saw it is open sourced.

**To Reproduce**
1. Go to 'https://github.com/WeBankFinTech/Qualitis#tips'
2. See `fes.js` is not open sourced, but we found this project: https://github.com/WeBankFinTech/fes.js

**Expected behavior**
Remove this `fes.js` is not open sourced statement. And if you can open source your front end code, it will be great.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Tangjiafeng** [comment]
Yes, we put qualitis ui source code in ui directory.
