### ISSUE TITLE
Qualitis system configuration

### ISSUE THREAD

**Issue by wosow** [WeBankFinTech/Qualitis#54]
**Describe the bug**
wedatasphere-linkis-0.9.4-dist.tar.gz
wedatasphere-qualitis-0.8.0.zip

How are the data sources for Qualitis system configuration configured in the figure below? Any examples
![image](https://user-images.githubusercontent.com/34565079/115978301-e03f3d00-a5b0-11eb-8a29-e8def55c8525.png)

**Comment by Tangjiafeng** [comment]
Just determine the gateway ip port of linkis.
