### ISSUE TITLE
Customize rule is translated to wrong SQL on min function

### ISSUE THREAD

**Issue by unklhe** [WeBankFinTech/Qualitis#57]
**Describe the bug**
Add a customize rule, and use the min fuction, the scala script is generated without coping the alias name

**To Reproduce**
1. add a customize rule
2. choose **min** stat function
3. fill other fields
4. save
5. from project -> rule ->execute task
6. check log, something likes:
val tmp1 = spark.sql("SELECT sales/projects AS mymin FROM test_hadoop.test_qualities WHERE pt_d='2021-05-26'");
val schemas = tmp1.schema.fields.map(f => f.name).toList
val newSchemas = schemas.map(s => s.replaceAll("[()]", "")).toList
val tmp2 = tmp1.toDF(newSchemas: _*)
tmp2.write.saveAsTable("test_qualitis_result.mid_application_19_20210527124203_868574");
tmp2.selectExpr("min(**sales/projects**) as value", "'QUALITIS20210527124203243_813453' as application_id", "'Long' as result_type", "'19' as rule_id", "'2021-05-27 12:42:03' as create_time").write.mode(org.apache.spark.sql.SaveMode.Append).

execute the script in spark shell could see excetion: org.apache.spark.sql.AnalysisException: cannot resolve '`sales`' given input columns: [mymin]; line 1 pos 4;

**Expected behavior**
use the alias name instead of origin expression

**Screenshots**
![image](https://user-images.githubusercontent.com/5634509/119769148-8d78de00-beec-11eb-990c-474c95da3b5f.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser :Chrome
 - Version: 0.8.0

**Comment by Tangjiafeng** [comment]
Thanks a lot!

We found this problem because spark dataframe selectExpr function cannot evaluate expression. That is to say, it is better to have only one field under the aggregate function - min.

You can do like this:

select min(res)
from (select a / b as res from db.table) tmp
where true
