### ISSUE TITLE
0.80版本中依赖的dss-appjoint-auth 0.9.0.WEBANK版本无法从仓库拉取

### ISSUE THREAD

**Issue by tarivs** [WeBankFinTech/Qualitis#58]
在gradle/dependencies.gradle文件中，存在以下引用

`"dss":"0.9.0.WEBANK",`
`dssAppJointAuth":"com.webank.wedatasphere.dss:dss-appjoint-auth:$versions.dss",`

maven从可以拉取到的最新版本为 0.7.0

DDS项目中，dss-appjoint-auth版本发布为：`0.7.0 -> 0.8.0 -> 0.9.0 -> 0.9.1`

建议将dss回退到 0.7.0 、0.8.0    或更新至  0.9.0   0.9.1

**Comment by ealpha** [comment]
"dss":"0.9.0.WEBANK"

这个版本，无法找到，😓

**Comment by mengfanzhen** [comment]
这个问题有解决吗？

**Comment by woxihuanzztt** [comment]
我是 手动改为0.7.0,目前可以成功运行,但不知道会不会对程序产生什么影响

**Comment by mengfanzhen** [comment]
> 我是 手动改为0.7.0,目前可以成功运行,但不知道会不会对程序产生什么影响

我也是手工改成了0.7.0，程序能跑起来，但是登录不进去，登录页面显示也不正常。

**Comment by mengfanzhen** [comment]
> 1判断是否是数据库连接失败 我本地数据库是8.0的,所以需要升级驱动版本 2登录的时候 检查后台,有几个打印的地方报空指针的问题,处理一下就行, 3页面部分中文乱码, 可以修改gradle配置,或者手动复制到资源文件到build指定的目录下便

感谢，页面已经跑起来了。

**Comment by momomobinx** [comment]
> 1判断是否是数据库连接失败 我本地数据库是8.0的,所以需要升级驱动版本
> 2登录的时候 检查后台,有几个打印的地方报空指针的问题,处理一下就行,
> 3页面部分中文乱码, 可以修改gradle配置,或者手动复制到资源文件到build指定的目录下便

gradle配置怎么修改

**Comment by Tangjiafeng** [comment]
建议使用0.9.1，对接的是dss appconn。
