### ISSUE TITLE
能提供一个 视频操作就好了，这样更方便别人看这个软件是不是自己想要的

### ISSUE THREAD

**Issue by JiPingWangPKI** [WeBankFinTech/Qualitis#59]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Tangjiafeng** [comment]
谢谢！我们会考虑整合使用视频！
