### ISSUE TITLE
qualities静态资源加载异常

### ISSUE THREAD

**Issue by duhanmin** [WeBankFinTech/Qualitis#64]
打包方式:
gradle clean distZip

显示和返回(200):
![image](https://user-images.githubusercontent.com/28647031/133883400-99f36ba3-77eb-4404-956f-045edfa296b6.png)

**Comment by woxihuanzztt** [comment]
感觉是gradle编译出现了问题,可以手动拷贝资源到 build/resource下去然后再访问

**Comment by momomobinx** [comment]
> 感觉是gradle编译出现了问题,可以手动拷贝资源到 build/resource下去然后再访问

除了手动拷贝还能别的方法吗？

**Comment by Tangjiafeng** [comment]
也可以采用nginx分离部署。默认spring web是要将静态文件放在conf/static下。
