### ISSUE TITLE
源码编译的脚本Gradle版本问题导致工程无法编译

### ISSUE THREAD

**Issue by wmcuit** [WeBankFinTech/Qualitis#70]
源码编译的脚本Gradle版本问题导致工程无法编译

build.gradle from 的gradle 文件夹，里的gradle-wrapper.properties 版本是6.6 改为 4.10.2才行

**Comment by wmcuit** [comment]
Could not find org.pentaho:pentaho-aggdesigner-algorithm:5.1.5-jhyde.
Required by:
    project :core/divider > project :core/common > org.apache.hive:hive-exec:1.2.1 > org.apache.calcite:calcite-core:1.2.0-incubating

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
 -

**Comment by Tangjiafeng** [comment]
gradle - 4.6
