### ISSUE TITLE
依赖的dss-0.9.0.webank的jar包和pom文件获取不到

### ISSUE THREAD

**Issue by Haibao233** [WeBankFinTech/Qualitis#71]
![f7dec06d7930415b0269241f4df19ac](https://user-images.githubusercontent.com/62696680/143976926-b4ef1cd0-b761-4147-9648-0cae554aaada.png)

**Comment by momomobinx** [comment]
下载dss 的0.9.0 版本 然后编译一下，就有相关包了

**Comment by Tangjiafeng** [comment]
Please use the latest release version
