### ISSUE TITLE
分别启动前后端，访问出现跨域问题

### ISSUE THREAD

**Issue by nonokang** [WeBankFinTech/Qualitis#74]
![kk_image](https://user-images.githubusercontent.com/13497810/148487727-fe4724dc-a088-47fa-b7eb-933aaae528b7.png)

**Comment by Su1024** [comment]
有这个问题 没人解决

**Comment by Tangjiafeng** [comment]
推荐使用最新的发布版本。

**Comment by LordHL** [comment]
这个问题怎么解决的呢
