### ISSUE TITLE
关于初始化任务成功，执行任务失败的问题

### ISSUE THREAD

**Issue by zhanghaicheng1** [WeBankFinTech/Qualitis#8]
问题描述：任务初始化成功，但是执行失败，提示获取yarn队列异常。

![qualitisError](https://user-images.githubusercontent.com/46189785/70587326-9e546780-1c04-11ea-862f-501dcf280c59.png)

期待回复！

**Comment by zhanghaicheng1** [comment]
单独部署的Qualitis，问题已定位，是Qualitis默认用户admin的队列和Dss用户的队列不一致导致的。我利用admin用户创建hive用户，并为hive赋admin权限，即可解决此问题。

**Comment by howeye** [comment]
https://github.com/WeBankFinTech/Qualitis/blob/master/docs/zh_CN/ch1/%E6%8E%A5%E5%85%A5Linkis%E6%96%87%E6%A1%A3.md
