### ISSUE TITLE
qualitis单机版安装完登录时提示后台接口异常

### ISSUE THREAD

**Issue by Forget-the-past** [WeBankFinTech/Qualitis#88]
qualitis单机版0.8.0版本单机版安装完后登录提示后台接口异常返回500状态码
![qualitis页面报错](https://user-images.githubusercontent.com/23069849/157812646-8e7f29e5-1423-495f-b831-31bc533fde66.PNG)
日志报错信息如下
![日志warnning](https://user-images.githubusercontent.com/23069849/157812701-42c5c478-bd7e-474a-a2f4-9457c905b34b.PNG)
![日志报错](https://user-images.githubusercontent.com/23069849/157812719-9a771e98-6572-4969-b6f5-a3cc349dc6bf.PNG)

**Comment by Tangjiafeng** [comment]
use 0.9.0, npe appears on the print of a log.
