### ISSUE TITLE
qualitis0.9版本配置参数问题

### ISSUE THREAD

**Issue by jmj1993** [WeBankFinTech/Qualitis#89]
![image](https://user-images.githubusercontent.com/23432986/158151937-5e881cb6-9e57-432e-ba5b-2b477d978be2.png)
![QQ图片20220314181240](https://user-images.githubusercontent.com/23432986/158152056-0791ec5d-ebf9-4adf-9cad-076b60ac98c4.png)
配置文件这几个参数默认情况下启动报错，能详细说明一下吗

**Comment by wu1wen2lin3** [comment]
我也碰到这个问题，在社区群中有回复了。
上面的参数随便填写，只需要符合IP和端口的数值就可以了。
![1647327603(1)](https://user-images.githubusercontent.com/14246631/158323707-e023d577-5210-4010-9ea0-edabbe003244.png)

**Comment by wu1wen2lin3** [comment]
> 
我也碰到这个问题，在社区群中有回复了。
上面的参数随便填写，只需要符合IP和端口的数值就可以了。

![image](https://user-images.githubusercontent.com/14246631/158323787-7a741272-2f25-4a16-a0d1-004b3d4f4104.png)

**Comment by Tangjiafeng** [comment]
Some configuration items that may be used in the future are not needed for the time being.
