### ISSUE TITLE
从dss1.0.1工作流页面跳转到qualitis0.9.0无法成功

### ISSUE THREAD

**Issue by xcdh123456** [WeBankFinTech/Qualitis#98]
1、使用Chrome83版本的浏览器可以跳转成功，而使用Chrome99版本的浏览器无法跳转成功，项目是对浏览器版本有要求吗？
2、使用Chrome83版本浏览器时，第一次请求点击工作流中qualitis节点时无法跳转，页面显示”哎呀，迷路了”，请求http://192.168.217.145:8090/qualitis/api/v1/redirect时Request Header中未携带cookie，Response Headers中含有cookie信息，而第二次请求是Request Header中携带cookie，是什么原因导致？

**Comment by Tangjiafeng** [comment]
建议申请域名，可以解决这个问题，比如：DSS 如果是 dss.xxx.com，QUALITIS 就是 dqm.xxx.com，保证域名中 xxx.com 一致即可。
